#!/usr/bin/env node
// cli/sequencer.js — standalone entry point for demo / direct invocation
// Supports: --root <dir>  --target <format>  --out <file>
//
// Targets: claude (→ CLAUDE.md), cursor (→ .cursorrules), json (→ JSON)

const fs = require('fs');
const path = require('path');

// Parse flags
const args = process.argv.slice(2);
function getFlag(name) {
  const i = args.indexOf(name);
  return i !== -1 && args[i + 1] ? args[i + 1] : null;
}

const root = getFlag('--root') || process.cwd();
const targetAlias = getFlag('--target') || 'stdout';
const outFile = getFlag('--out') || null;

const TARGET_ALIASES = {
  claude: 'claude-md',
  cursor: 'cursorrules',
  mcp: 'json',
  json: 'json',
  stdout: 'stdout',
};
const target = TARGET_ALIASES[targetAlias] || targetAlias;

// ---- Inline context.md parser (not yet in parsers/intent.js) ----
function parseContextMd(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const match = content.match(/^---\n[\s\S]*?\n---\n?([\s\S]*)$/);
  const body = match ? match[1] : content;
  const mtime = fs.statSync(filePath).mtime.toISOString();
  return [{
    source: '.intent/context.md',
    sourceType: 'intent',
    kind: 'context',
    content: body.trim(),
    timestamp: mtime,
    metadata: {},
  }];
}

// ---- Cursorrules emitter ----
function emitCursorrules(chunks) {
  const lines = [];
  const projectName = getProjectName(chunks, root);

  lines.push(`# ${projectName} — cursor rules`);
  lines.push(`# Generated by phewsh sequencer from .intent/ | ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // Identity first: what this project is
  const identity = chunks.filter(c => c.kind === 'identity');
  if (identity.length > 0) {
    lines.push('## Project');
    lines.push(identity[0].content.split('\n')[0].replace(/^#\s*/, '').trim());
    // Include a short excerpt (first non-empty paragraph)
    const paras = identity[0].content.split('\n\n').filter(p => p.trim() && !p.startsWith('#'));
    if (paras[0]) lines.push(paras[0].trim().replace(/\n/g, ' '));
    lines.push('');
  }

  // Constraints — always first per compass spec
  const constraints = chunks.filter(c => c.kind === 'constraint');
  if (constraints.length > 0) {
    lines.push('## Constraints');
    for (const c of constraints) {
      for (const l of c.content.split('\n').filter(l => l.trim())) {
        lines.push(`- ${l.replace(/^[-*]\s*/, '')}`);
      }
    }
    lines.push('');
  }

  // Current state — what's happening right now
  const state = chunks.filter(c => c.kind === 'state');
  if (state.length > 0) {
    lines.push('## Current State');
    for (const s of state) {
      const summary = s.content.split('\n').filter(l => l.trim() && !l.startsWith('#')).slice(0, 3);
      summary.forEach(l => lines.push(`- ${l.replace(/^[-*]\s*/, '')}`));
    }
    lines.push('');
  }

  // Build plan (plan.md) — separate from tech context
  const planChunks = chunks.filter(c => c.kind === 'context' && c.source.includes('plan'));
  if (planChunks.length > 0) {
    lines.push('## Build Plan');
    for (const c of planChunks) {
      const relevant = c.content.split('\n')
        .filter(l => l.trim() && !l.startsWith('```') && !l.startsWith('#'))
        .slice(0, 10);
      relevant.forEach(l => lines.push(l.startsWith('- ') ? l : `- ${l.replace(/^\*\*/, '').replace(/\*\*:/, ':')}`));
    }
    lines.push('');
  }

  // Technical context (context.md and others, not plan)
  const ctx = chunks.filter(c => c.kind === 'context' && !c.source.includes('plan'));
  if (ctx.length > 0) {
    lines.push('## Technical Context');
    for (const c of ctx) {
      const relevant = c.content.split('\n')
        .filter(l => l.trim() && !l.startsWith('```') && !l.startsWith('#'))
        .slice(0, 8);
      relevant.forEach(l => lines.push(l.startsWith('- ') ? l : `- ${l.replace(/^\*\*/, '').replace(/\*\*:/, ':')}`));
    }
    lines.push('');
  }

  // Behavioral rules / feedback
  const feedback = chunks.filter(c => c.kind === 'feedback');
  if (feedback.length > 0) {
    lines.push('## Rules');
    for (const f of feedback) {
      lines.push(`- ${f.content.split('\n')[0]}`);
    }
    lines.push('');
  }

  // Active next task
  const actions = chunks.filter(c => c.kind === 'action');
  if (actions.length > 0) {
    lines.push('## Active Task');
    for (const a of actions) {
      const task = a.content.split('\n').filter(l => l.trim()).slice(0, 4);
      task.forEach(l => lines.push(l.startsWith('-') ? l : `- ${l}`));
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ---- JSON emitter ----
function emitJson(chunks) {
  const projectName = getProjectName(chunks, root);
  const payload = {
    project: projectName,
    generated: new Date().toISOString(),
    source: '.intent/',
    chunks: chunks.map(c => ({
      kind: c.kind,
      source: c.source,
      weight: Math.round(c.weight * 1000) / 1000,
      content: c.content,
    })),
    summary: {
      identity: chunks.filter(c => c.kind === 'identity').map(c => c.content.split('\n')[0]).join(' / '),
      state: chunks.filter(c => c.kind === 'state').map(c =>
        c.content.split('\n').filter(l => l.trim() && !l.startsWith('#'))[0] || ''
      ).filter(Boolean).join('; '),
      nextTask: (chunks.find(c => c.kind === 'action') || chunks.find(c => c.kind === 'state' && c.source.includes('next')))?.content.split('\n')[0] || '',
    },
  };
  return JSON.stringify(payload, null, 2);
}

function getProjectName(chunks, cwd) {
  for (const chunk of chunks) {
    if (chunk.sourceType === 'intent' && chunk.kind === 'identity') {
      const nameMatch = chunk.content.match(/^#\s+(.+)/m);
      if (nameMatch) return nameMatch[1].trim();
    }
  }
  return path.basename(cwd);
}

// ---- Main ----
async function main() {
  // Load the existing sequencer pipeline
  const seqPath = path.join(__dirname, 'lib/sequencer');
  const { sequence } = require(path.join(seqPath, 'index'));
  const { discover } = require(path.join(seqPath, 'discover'));
  const { rank } = require(path.join(seqPath, 'ranker'));
  const { compress } = require(path.join(seqPath, 'compressor'));
  const intentParser = require(path.join(seqPath, 'parsers/intent'));

  // Run normal discovery
  const sources = discover(root);

  // Parse all recognized sources
  let chunks = [];
  for (const source of sources) {
    const parsed = intentParser.parse ? intentParser.parse(source) : [];
    chunks.push(...parsed);
  }

  // Manually handle context.md (not yet in discover's FILE_PARSERS)
  const contextPath = path.join(root, '.intent', 'context.md');
  if (fs.existsSync(contextPath)) {
    chunks.push(...parseContextMd(contextPath));
  }

  // Rank + compress
  chunks = rank(chunks);
  chunks = compress(chunks, 'standard');

  let output;
  if (target === 'claude-md') {
    const emitter = require(path.join(seqPath, 'emitters/claude-md'));
    output = emitter.emit(chunks, { projectName: getProjectName(chunks, root) });
  } else if (target === 'cursorrules') {
    output = emitCursorrules(chunks);
  } else if (target === 'json') {
    output = emitJson(chunks);
  } else if (target === 'stdout') {
    const emitter = require(path.join(seqPath, 'emitters/stdout'));
    emitter.emit(chunks, { explain: false, sources });
    return;
  } else {
    console.error(`Unknown target: ${target}. Use: claude, cursor, json`);
    process.exit(1);
  }

  if (outFile) {
    fs.writeFileSync(outFile, output + '\n');
    console.error(`Wrote ${target} output → ${outFile}`);
  } else {
    console.log(output);
  }
}

main().catch(err => {
  console.error(err.message);
  process.exit(1);
});
